package flow;

import java.sql.SQLException;

import com.itsconv.model.Customer;
import com.itsconv.repository.CustomerRepository;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026년 7월 24일 (금) 오후 4시 32분 49초
 */
public class LookupCustomer extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026년 7월 24일 (금) 오후 4시 32분 49초
	 */
	public LookupCustomer() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026년 7월 24일 (금) 오후 4시 32분 49초
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		/*
		 * DB 오류가 발생해도 미등록 고객 흐름으로 진행할 수 있도록
		 * 조회 결과를 실패 기본값으로 초기화한다.
		 */
		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_CUSTOMER_FOUND
		).setValue(false);

		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_DB_SUCCESS
		).setValue(false);

		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_CUST_NAME
		).setValue("");

		try {
			/*
			 * 1. ANI에서 숫자가 아닌 문자를 제거한다.
			 */
			String ani = mySession
					.getVariableField("session:ani")
					.getStringValue();

			String phoneNumber = ani == null
					? "" : ani.replaceAll("[^0-9]", "");

			/*
			 * 2. ANI를 조회 번호와 콜백 번호의 기본값으로 저장한다.
			 * 사용자가 다른 번호를 입력하면 이후 입력 단계에서 덮어쓴다.
			 */
			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_LOOKUP_PHONE
			).setValue(phoneNumber);

			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CALLBACK_NUMBER
			).setValue(phoneNumber);

			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO,
					"고객 DB 조회 시작 - ANI: " + phoneNumber
			);

			/*
			 * 3. 전화번호로 고객 정보를 조회한다.
			 */
			CustomerRepository repository = new CustomerRepository();
			Customer customer = repository.findByPhone(phoneNumber);

			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_DB_SUCCESS
			).setValue(true);

			if (customer == null) {
				mySession.getTraceOutput().writeln(
						com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO,
						"미등록 고객 - ANI: " + phoneNumber
				);
				return;
			}

			/*
			 * 4. 등록 고객 정보를 프로젝트 변수에 저장한다.
			 */
			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CUSTOMER_FOUND
			).setValue(true);

			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CUST_NAME
			).setValue(customer.getCustomerName());

			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO,
					"등록 고객 조회 성공 - 고객명: "
							+ customer.getCustomerName()
			);

		} catch (SQLException e) {
			/*
			 * DB 장애는 오류 로그만 남긴다.
			 * 초기 실패 값이 유지되므로 미등록 고객 흐름으로 진행한다.
			 */
			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_ERROR,
					"고객 DB 조회 실패: " + e.getMessage()
			);

		} catch (Exception e) {
			/*
			 * 예상하지 못한 오류도 콜에 노출하지 않고
			 * 미등록 고객 흐름으로 진행한다.
			 */
			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_ERROR,
					"고객 조회 처리 오류: " + e.getMessage()
			);
		}
	}
		

	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 5시 54분 01초
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("DBSuccess", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
