package flow;

import com.itsconv.model.Customer;
import com.itsconv.repository.CustomerRepository;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026년 7월 24일 (금) 오후 4시 32분 49초
 */
public class LookupCustomer extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026년 7월 24일 (금) 오후 4시 32분 49초
	 */
	public LookupCustomer() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026년 7월 24일 (금) 오후 4시 32분 49초
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {
		mySession.getVariableField("session", "ani").setValue("01064178454");

		boolean customerFound = false;
		boolean dbSuccess = false;
		String custName = "";
		String phoneNumber = "";
		String ani = "";

		try {
			/*
			 * 1. AAOD 세션에 저장된 ANI를 읽고
			 * 하이픈, 공백 등 숫자가 아닌 문자를 제거한다.
			 */
			ani = mySession.getVariableField("session", "ani").getStringValue();

			if (ani != null) {
				phoneNumber = ani.replaceAll("[^0-9]", "");
			}

			/*
			 * 2. ANI를 조회 번호와 콜백 번호의 기본값으로 저장한다.
			 * 사용자가 다른 번호를 입력하면 이후 입력 단계에서 덮어쓴다.
			 */
			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_LOOKUP_PHONE
			).setValue(phoneNumber);

			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CALLBACK_NUMBER
			).setValue(phoneNumber);

			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO,
					"고객 DB 조회 시작 - ANI: " + phoneNumber
			);

			/*
			 * 3. 전화번호로 고객 정보를 조회한다.
			 */
			Customer customer = new CustomerRepository().findByPhone(phoneNumber);
			
			dbSuccess = true; //고객이 없어도 DB 조회 자체는 성공으로 처리한다.
			
			if (customer != null) {
				customerFound = true;
				custName = customer.getCustomerName();
			}

		} catch (Exception e) {
			//DB 장애나 예상하지 못한 오류가 발생해도 예외를 다시 던지지 않는다.
			System.out.println("Lookup customer faild: " + e.getMessage());
			
			mySession.getTraceOutput().writeln(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_ERROR, 
					"Lookup Customer faild: " + e.getMessage());//AAOD Trace 로그에 남기는 용도
		}

		// 5. 조회 결과를 프로젝트 변수에 저장한다.
		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_CUSTOMER_FOUND
		).setValue(customerFound);

		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_DB_SUCCESS
		).setValue(dbSuccess);

		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_CUST_NAME
		).setValue(custName);

		// 등록 여부와 고객명을 포함한 최종 조회 결과를 로그에 남긴다.
		mySession.getVariableField("call", "customerFound").setValue(customerFound);
		mySession.getVariableField("call", "custName").setValue(custName);

		System.out.println("고객 조회 결과: phoneNumber(ani)= " + phoneNumber
				+", registered =" +customerFound + ", customerName= " + custName
				);

	}
		

	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026년 7월 30일 (목) 오전 9시 27분 21초
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("DBSuccess", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
