package flow;

import com.itsconv.util.CallCompletionTracker;
import com.itsconv.util.IvrLogger;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026년 7월 30일 (목) 오후 1시 30분 44초
 */
public class OnDisconnectLog extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026년 7월 30일 (목) 오후 1시 30분 44초
	 */
	public OnDisconnectLog() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch".
	 *
	 * Using this method, you have access to all session variables through the
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026년 7월 30일 (목) 오후 1시 30분 44초
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {
		String sessionId = mySession.getVariableField("session", "sessionid").getStringValue();

		if (CallCompletionTracker.wasCompleted(sessionId)) {
			// 등록 성공/실패 안내(CallEndLog) 또는 재시도초과 안내(RetryLog)를 이미 거친 콜이
			// 정상 종료(Disconnect/ExceedDisconnect)된 뒤에 플랫폼이 뒤따라 보내는 이벤트다.
			// 실제 중간 이탈이 아니므로 문구를 구분해서 남긴다.
			IvrLogger.log("OnDisconnectLog", "OnDisconnect 이벤트 발생 - 정상 종료");
		} else {
			IvrLogger.log("OnDisconnectLog", "OnDisconnect 이벤트 발생 - 콜 중간 이탈");
		}
	}

	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026년 7월 31일 (금) 오전 9시 49분 23초
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("EndReturn1", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
