package flow;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 1시 54분 32초
 */
public class RegisterCallback extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 1시 54분 32초
	 */
	public RegisterCallback() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 1시 54분 32초
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {
		
		/*
		 * API 호출 중 오류가 발생해도 실패 값이 유지되도록
		 * 먼저 콜백 등록 결과를 초기화한다.
		 */
		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_API_SUCCESS
		).setValue(false);

		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_CALLBACK_ID
		).setValue("");

		HttpURLConnection connection = null;

		try {
			/*
			 * 1. 등록/미등록 고객 입력 폼에서 콜백 번호를 읽는다.
			 * 숫자를 입력한 경우에만 ANI 기본값을 새 번호로 덮어쓴다.
			 * # 입력 시에는 숫자가 없으므로 기존 ANI 값이 유지된다.
			 */
			String customerFoundValue = mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CUSTOMER_FOUND
			).getStringValue();

			String inputValue;

			if ("true".equalsIgnoreCase(customerFoundValue)) {
				inputValue = mySession.getVariableField(
						IProjectVariables.REGISTERED_GUIDE,
						IProjectVariables.REGISTERED_GUIDE_FIELD_VALUE
				).getStringValue();
			} else {
				inputValue = mySession.getVariableField(
						IProjectVariables.UNREGISTERED_GUIDE,
						IProjectVariables.UNREGISTERED_GUIDE_FIELD_VALUE
				).getStringValue();
			}

			String enteredNumber = inputValue == null
					? "" : inputValue.replaceAll("[^0-9]", "");

			if (!enteredNumber.isEmpty()) {
				mySession.getVariableField(
						IProjectVariables.CALL,
						IProjectVariables.CALL_FIELD_CALLBACK_NUMBER
				).setValue(enteredNumber);
			}

			String callbackNumber = mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CALLBACK_NUMBER
			).getStringValue();

			String custName = mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CUST_NAME
			).getStringValue();

			if (callbackNumber == null) {
				callbackNumber = "";
			}

			if (custName == null) {
				custName = "";
			}

			/*
			 * 2. JSON 문자열에 포함될 수 있는 특수 문자를 이스케이프한다.
			 */
			String escapedCallbackNumber = callbackNumber
					.replace("\\", "\\\\")
					.replace("\"", "\\\"")
					.replace("\b", "\\b")
					.replace("\f", "\\f")
					.replace("\n", "\\n")
					.replace("\r", "\\r")
					.replace("\t", "\\t");

			String escapedCustName = custName
					.replace("\\", "\\\\")
					.replace("\"", "\\\"")
					.replace("\b", "\\b")
					.replace("\f", "\\f")
					.replace("\n", "\\n")
					.replace("\r", "\\r")
					.replace("\t", "\\t");

			String requestJson =
					"{\"callbackNumber\":\"" + escapedCallbackNumber
					+ "\",\"ani\":\"" + escapedCallbackNumber
					+ "\",\"custName\":\"" + escapedCustName + "\"}";

			byte[] requestBytes = requestJson.getBytes("UTF-8");

			/*
			 * 3. 콜백 등록 API에 JSON 요청을 전송한다.
			 */
			URL url = new URL(
					"http://192.168.40.200:18080/api/v1/callbacks"
			);
			
			connection = (HttpURLConnection) url.openConnection();
			connection.setRequestMethod("POST");
			connection.setConnectTimeout(3000);
			connection.setReadTimeout(3000);
			connection.setDoOutput(true);
			connection.setRequestProperty(
					"Content-Type",
					"application/json; charset=UTF-8"
			);
			connection.setFixedLengthStreamingMode(requestBytes.length);

			OutputStream outputStream = connection.getOutputStream();

			try {
				outputStream.write(requestBytes);
				outputStream.flush();
			} finally {
				outputStream.close();
			}

			int httpStatus = connection.getResponseCode();
			InputStream inputStream;

			if (httpStatus == HttpURLConnection.HTTP_OK) {
				inputStream = connection.getInputStream();
			} else {
				inputStream = connection.getErrorStream();
			}

			StringBuilder responseBuilder = new StringBuilder();

			if (inputStream != null) {
				BufferedReader reader = new BufferedReader(
						new InputStreamReader(inputStream, "UTF-8")
				);

				try {
					String line;

					while ((line = reader.readLine()) != null) {
						responseBuilder.append(line);
					}
				} finally {
					reader.close();
				}
			}

			String responseJson = responseBuilder.toString();

			/*
			 * 4. 응답 JSON 문자열에서 code와 callbackId를 직접 추출한다.
			 */
			Matcher codeMatcher = Pattern.compile(
					"\"code\"\\s*:\\s*\"([^\"]*)\""
			).matcher(responseJson);

			Matcher callbackIdMatcher = Pattern.compile(
					"\"callbackId\"\\s*:\\s*\"([^\"]*)\""
			).matcher(responseJson);

			String code = codeMatcher.find()
					? codeMatcher.group(1) : "";

			String callbackId = callbackIdMatcher.find()
					? callbackIdMatcher.group(1) : "";

			/*
			 * HTTP 상태가 200이고 응답 code가 0000인 경우만 성공이다.
			 */
			if (httpStatus == HttpURLConnection.HTTP_OK
					&& "0000".equals(code)) {

				mySession.getVariableField(
						IProjectVariables.CALL,
						IProjectVariables.CALL_FIELD_API_SUCCESS
				).setValue(true);

				mySession.getVariableField(
						IProjectVariables.CALL,
						IProjectVariables.CALL_FIELD_CALLBACK_ID
				).setValue(callbackId);

				mySession.getTraceOutput().writeln(
						com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO,
						"콜백 등록 성공 - callbackId: " + callbackId
				);

			} else {
				mySession.getTraceOutput().writeln(
						com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_ERROR,
						"콜백 등록 실패 - HTTP 상태: " + httpStatus
								+ ", 응답 code: " + code
				);
			}

		} catch (Exception e) {

			/*
			 * API 연결이나 응답 처리 중 오류가 발생해도
			 * 예외를 다시 던지지 않고 실패로 처리한다.
			 */
			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_API_SUCCESS
			).setValue(false);

			mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CALLBACK_ID
			).setValue("");

			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_ERROR,
					"콜백 등록 실패: " + e.getMessage()
			);

		} finally {
			if (connection != null) {
				connection.disconnect();
			}
		}

	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 5시 54분 01초
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("untitledDisconnect1", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
