package flow;

import com.itsconv.http.CallbackApiClient;
import com.itsconv.http.CallbackApiResult;
import com.itsconv.util.IvrLogger;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 1시 54분 32초
 */
public class RegistCallback extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 1시 54분 32초
	 */
	public RegistCallback() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 1시 54분 32초
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {
		IvrLogger.log("RegistCallback", "단계 진입 - 콜백 등록 API 호출 시작");

		CallbackApiResult result;

		try {
			/*
			 * 1. AAOD 세션에 저장된 실제 발신번호를 읽는다.
			 */
			String ani = mySession
					.getVariableField("session", "ani")
					.getStringValue();

			/*
			 * 2. 앞 단계에서 고객이 확정한 콜백 번호를 읽는다.
			 */
			String callbackNumber = mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CALLBACK_NUMBER
			).getStringValue();

			/*
			 * 3. 등록 고객이면 DB 조회 시 저장된 고객명을 읽는다.
			 * 미등록 고객은 빈 문자열을 사용한다.
			 */
			String custName = mySession.getVariableField(
					IProjectVariables.CALL,
					IProjectVariables.CALL_FIELD_CUST_NAME
			).getStringValue();

			/*
			 * 4. 확정된 콜백 정보로 콜백 등록 API를 호출한다.
			 */
			IvrLogger.log("RegistCallback", "API 요청 - callbackNumber=" + callbackNumber
					+ ", ani=" + ani
					+ ", custName=" + custName
			);

			result = CallbackApiClient.getInstance()
					.registerCallback(
							callbackNumber,
							ani,
							custName
					);

		} catch (Exception e) {
			/*
			 * AAOD 세션 변수 처리 중 발생한 오류도
			 * 콜에 노출하지 않고 실패 결과로 처리한다.
			 */
			IvrLogger.log("RegistCallback", "API 호출 중 예외 발생 - " + e.getMessage());
			result = CallbackApiResult.failure(e.getMessage());
		}

		/*
		 * 5. API 호출 결과와 접수 ID를 IVR 분기용 변수에 저장한다.
		 */
		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_API_SUCCESS // api 호출 성공 결과를 AAOD변수 api_seccess에 저장
		).setValue(result.isSuccess());

		mySession.getVariableField(
				IProjectVariables.CALL,
				IProjectVariables.CALL_FIELD_CALLBACK_ID
		).setValue(result.getCallbackId());

		if (result.isSuccess()) {
			IvrLogger.log("RegistCallback", "API 호출 결과 - 성공, callbackId=" + result.getCallbackId());

			/*
			 * 6. 실제로 등록됐는지 확인용 GET 요청을 보내되, 방금 등록한 callbackId 항목만 로그로 남긴다.
			 */
			String registeredEntry = CallbackApiClient.getInstance().fetchRegisteredCallback(result.getCallbackId());
			IvrLogger.log("RegistCallback", "등록 확인(GET /api/v1/callbacks) - " + registeredEntry);

			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_INFO,
					"콜백 등록 성공 - callbackId: "
							+ result.getCallbackId()
			);
		} else {
			IvrLogger.log("RegistCallback", "API 호출 결과 - 실패, reason=" + result.getFailureReason());

			mySession.getTraceOutput().writeln(
					com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_ERROR,
					"콜백 등록 실패: "
							+ result.getFailureReason()
			);
		}
	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2026년 7월 31일 (금) 오전 9시 49분 23초
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("RegistResult", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
