package ko.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 4시 58분 53초
 */
public class ivr extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(18);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: its-1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-1", "its-1.wav", "죄송합니다. 지금은 업무시간이 종료되었습니다."); 

		// phrase: its-2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-2", "its-2.wav", "산모 또는 배우자의 핸드폰 번호 열한 자리를 눌러주십시오. 지금 거신 전화번호를 누르시려면 우물정자를 눌러주십시오."); 

		// phrase: its-3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-3", "its-3.wav", "번호를 남겨주시면 다음 업무일에 연락드리겠습니다. 연락받으실 핸드폰 번호 열한 자리를 눌러주십시오. 지금 거신 전화번호를 남기시려면 우물정자를 눌러주십시오"); 

		// phrase: its-4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-4", "its-4.wav", "맞으면 1번, 틀리면 2번을 눌러주십시오"); 

		// phrase: its-5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-5", "its-5.wav", "등록되었습니다. 확인후 연락드리도록 하겠습니다. 이용해주셔서 감사합니다."); 

		// phrase: its-6
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-6", "its-6.wav", "이용방법을 확인하신 후 다시 이용해주십시오"); 

		// phrase: its-7
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-7", "its-7.wav", "입력이 늦었습니다."); 

		// phrase: its-8
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-8", "its-8.wav", "잘못 누르셨습니다"); 

		// phrase: its-9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "its-9", "its-9.wav", "이용방법을 확인하신 후 다시 이용해주십시오."); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 5시 54분 01초
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(ivr.PHRASE_MAP, phraseName));
	}
}
