package ko.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2026년 7월 27일 (월) 오후 4시 55분 00초
 */
public class std_ko_kr extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(192);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: std_0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0", "0030.wav", ":0"); 

		// phrase: std_0h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0h", "0064.wav", ":0h"); 

		// phrase: std_0t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0t", "0045.wav", ":0t"); 

		// phrase: std_1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1", "0031.wav", ":1"); 

		// phrase: std_10
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10", "0040.wav", ":10"); 

		// phrase: std_100
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100", "0041.wav", ":100"); 

		// phrase: std_1000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000", "0042.wav", ":1000"); 

		// phrase: std_10000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10000", "0043.wav", ":10000"); 

		// phrase: std_100000000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100000000", "0044.wav", ":100000000"); 

		// phrase: std_10h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10h", "0074.wav", ":10h"); 

		// phrase: std_10t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10t", "0055.wav", ":10t"); 

		// phrase: std_11h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_11h", "0075.wav", ":11h"); 

		// phrase: std_12h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_12h", "0076.wav", ":12h"); 

		// phrase: std_1h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1h", "0065.wav", ":1h"); 

		// phrase: std_1t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1t", "0046.wav", ":1t"); 

		// phrase: std_2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2", "0032.wav", ":2"); 

		// phrase: std_20t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_20t", "0056.wav", ":20t"); 

		// phrase: std_2h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2h", "0066.wav", ":2h"); 

		// phrase: std_2t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2t", "0047.wav", ":2t"); 

		// phrase: std_3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3", "0033.wav", ":3"); 

		// phrase: std_30t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_30t", "0057.wav", ":30t"); 

		// phrase: std_3h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3h", "0067.wav", ":3h"); 

		// phrase: std_3t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3t", "0048.wav", ":3t"); 

		// phrase: std_4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4", "0034.wav", ":4"); 

		// phrase: std_40t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_40t", "0058.wav", ":40t"); 

		// phrase: std_4h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4h", "0068.wav", ":4h"); 

		// phrase: std_4t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4t", "0049.wav", ":4t"); 

		// phrase: std_5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5", "0035.wav", ":5"); 

		// phrase: std_50t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_50t", "0059.wav", ":50t"); 

		// phrase: std_5h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5h", "0069.wav", ":5h"); 

		// phrase: std_5t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5t", "0050.wav", ":5t"); 

		// phrase: std_6
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6", "0036.wav", ":6"); 

		// phrase: std_60t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_60t", "0060.wav", ":60t"); 

		// phrase: std_6h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6h", "0070.wav", ":6h"); 

		// phrase: std_6t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6t", "0051.wav", ":6t"); 

		// phrase: std_7
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7", "0037.wav", ":7"); 

		// phrase: std_70t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_70t", "0061.wav", ":70t"); 

		// phrase: std_7h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7h", "0071.wav", ":7h"); 

		// phrase: std_7t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7t", "0052.wav", ":7t"); 

		// phrase: std_8
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8", "0038.wav", ":8"); 

		// phrase: std_80t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_80t", "0062.wav", ":80t"); 

		// phrase: std_8h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8h", "0072.wav", ":8h"); 

		// phrase: std_8t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8t", "0053.wav", ":8t"); 

		// phrase: std_9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9", "0039.wav", ":9"); 

		// phrase: std_90t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_90t", "0063.wav", ":90t"); 

		// phrase: std_9h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9h", "0073.wav", ":9h"); 

		// phrase: std_9t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9t", "0054.wav", ":9t"); 

		// phrase: std_a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_a", "0001.wav", ":a"); 

		// phrase: std_b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_b", "0002.wav", ":b"); 

		// phrase: std_boon
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_boon", "0077.wav", "boon"); 

		// phrase: std_c
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_c", "0003.wav", ":c"); 

		// phrase: std_cent
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_cent", "0078.wav", "cent"); 

		// phrase: std_d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_d", "0004.wav", ":d"); 

		// phrase: std_dollar
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dollar", "0079.wav", "dollar"); 

		// phrase: std_e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e", "0005.wav", ":e"); 

		// phrase: std_f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_f", "0006.wav", ":f"); 

		// phrase: std_g
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_g", "0007.wav", ":g"); 

		// phrase: std_h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_h", "0008.wav", ":h"); 

		// phrase: std_i
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_i", "0009.wav", ":i"); 

		// phrase: std_il
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_il", "0080.wav", "il"); 

		// phrase: std_j
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_j", "0010.wav", ":j"); 

		// phrase: std_jeom
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_jeom", "0081.wav", "jeom"); 

		// phrase: std_jeongo
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_jeongo", "0082.wav", "jeongo"); 

		// phrase: std_k
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_k", "0011.wav", ":k"); 

		// phrase: std_l
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_l", "0012.wav", ":l"); 

		// phrase: std_m
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_m", "0013.wav", ":m"); 

		// phrase: std_n
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_n", "0014.wav", ":n"); 

		// phrase: std_nyeon
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_nyeon", "0083.wav", "nyeon"); 

		// phrase: std_o
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_o", "0015.wav", ":o"); 

		// phrase: std_ohoo
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_ohoo", "0084.wav", "ohoo"); 

		// phrase: std_ojeon
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_ojeon", "0085.wav", "ojeon"); 

		// phrase: std_p
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_p", "0016.wav", ":p"); 

		// phrase: std_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_q", "0017.wav", ":q"); 

		// phrase: std_r
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_r", "0018.wav", ":r"); 

		// phrase: std_s
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_s", "0019.wav", ":s"); 

		// phrase: std_shi
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_shi", "0088.wav", "shi"); 

		// phrase: std_sil_dot_050
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_050", "1130.wav", "sil.050"); 

		// phrase: std_sil_dot_100
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_100", "1131.wav", "sil.100"); 

		// phrase: std_sil_dot_200
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_200", "1132.wav", "sil.200"); 

		// phrase: std_sil_dot_300
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_300", "1133.wav", "sil.300"); 

		// phrase: std_sil_dot_400
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_400", "1134.wav", "sil.400"); 

		// phrase: std_sil_dot_500
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_500", "1135.wav", "sil.500"); 

		// phrase: std_sil_dot_600
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_dot_600", "1136.wav", "sil.600"); 

		// phrase: std_t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_t", "0020.wav", ":t"); 

		// phrase: std_u
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_u", "0021.wav", ":u"); 

		// phrase: std_v
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_v", "0022.wav", ":v"); 

		// phrase: std_w
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_w", "0023.wav", ":w"); 

		// phrase: std_wall
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_wall", "0086.wav", "wall"); 

		// phrase: std_won
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_won", "0087.wav", "won"); 

		// phrase: std_x
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_x", "0024.wav", ":x"); 

		// phrase: std_y
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_y", "0025.wav", ":y"); 

		// phrase: std_z
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_z", "0026.wav", ":z"); 

		// phrase: std__dash
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std__dash", "0029.wav", ":-"); 

		// phrase: std__hash
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std__hash", "0028.wav", ":#"); 

		// phrase: std__minus
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std__minus", "0029.wav", ":-"); 

		// phrase: std__star
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std__star", "0027.wav", ":*"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2026년 7월 30일 (목) 오전 9시 26분 11초
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(std_ko_kr.PHRASE_MAP, phraseName));
	}
}
