package ko.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2026년 7월 28일 (화) 오후 1시 11분 05초
 */
public class hash extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for hash.
    */
    public hash() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("hash.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

